site_name: Simulated Microscopy Documentation

theme:
  name: material
  features:
    - navigation.footer

nav:
    - index.md
    - installation.md
    - example-usage.md
    - api.md

plugins:
  - search
  - mkdocstrings

repo_url: https://github.com/rhoitink/simulatedmicroscopy
