site_name: Simulated Microscopy Documentation

theme:
  name: material
  features:
    - navigation.footer

nav:
    - index.md
    - installation.md
    - data-generation-example.md
    - api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: false
            show_source: false

repo_url: https://github.com/rhoitink/simulatedmicroscopy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
