name: Deploy documentation

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[docs]
    - name: Build docs with mkdocs
      run: |
        # build docs to site dir
        mkdocs build
    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
